name: "Vault"
main: com.example.vault.VaultPlugin
version: v1.3
api-version: 1.13
description: Internal Economy provider like Vault 2.0 (no Vault.jar dependency)
softdepend: [LuckPerms, PlaceholderAPI]
commands:
  balance:
    description: Show your current balance
    usage: /balance
  pay:
    description: Send money to another player
    usage: /pay <player> <amount>
    aliases: [pagar]
  vault:
    description: Admin command for Vault
    usage: /vault reload|update
permissions:
  vault.balance:
    description: Allows using /balance
    default: true
  vault.pay:
    description: Allows using /pay menu and direct payments
    default: true
  vault.pay.bypass_min:
    description: Bypass minimum amount limit
    default: op
  vault.pay.bypass_max:
    description: Bypass maximum amount limit
    default: op